// src/constants/labels.js
export const FIELD_LABELS = {
  // 基础信息
  vehicleModel: '工程代码 / Vehicle Model',
  modelYear: '生产年份 / Model Year',
  vin: '车架号 / VIN',
  tester: '测试人员 / Tester',
  mileage: '总里程数 / Odometer',
  address: '测试地址 / Testing Location',
  architecture: '总线架构 / Architecture',
  iviModule: '娱乐系统 / IVI Module',
  commModule: '通讯模块 / Comm Module',
  packagePhoto: '套餐包照片 / Package Photo',
  envPhoto: '现场环境照片 / Env Photo',

  // 按钮文字
  executeTesting: '执行测试 / EXECUTE TESTING',
  viewHistory: '测试历史 / TEST HISTORY',
  caseManagement: '用例管理 / CASE MANAGEMENT',
  managerDashboard: '管理看板 / MANAGER DASHBOARD',
  pdcaCenter: '缺陷中心 / PDCA DEFECT CENTER',

  // Dashboard KPI
  globalPassRate: '全局通过率 / Global Pass Rate',
  casesPassed: '通过用例数 / Cases Passed',
  casesFailed: '失败用例数 / Cases Failed',
  recentDefectFeed: '实时缺陷流 / Recent Defect Feed',
  topProblematicCases: '问题最多用例 / Top Problematic Cases',
  // Section titles
  modelPassRateComparison: '通过率对比 / Model Pass Rate Comparison',
  dailyTestingVolume: '每日测试量 (用例) / Daily Testing Volume (Cases)',
  topFailedCases: '最高失败用例 / Top Failed Cases',
  recentDefectFeedTitle: '实时缺陷流 / Recent Defect Feed',
  // PDCA 看板列标题
  statusPlan: 'P (Plan) 待处理',
  statusDo: 'D (Do) 修复中',
  statusCheck: 'C (Check) 待验证',
  statusAct: 'A (Act) 已闭环',
  assignee: '负责人 / Assignee',
  rootCause: '根因分析 / Root Cause',
  actionNotes: '对策与闭环 / Action & Solution',

  // 其它常用文字（可自行补充）
  timingCapture: '耗时抓取 / Timing Capture',
  finalVerdict: '最终判定 / Final Verdict',
  captureEvidence: '抓取证据 / Capture Evidence',
  caseNavigator: '用例导航 / Case Navigator',
  issueList: '问题列表 / Issue List',
  filterCases: '用例筛选 / Filter Cases',
  sessionTitle: '测试会话 / Test Session',
  backToDashboard: '返回看板 / Back to Dashboard',
  defectKanbanBoard: '缺陷看板 / Defect Kanban Board',
  clickBarToDrillDown: '点击图表下钻 / Click Bar To Drill Down',
  passRatePercent: '通过率 (%) / Pass Rate (%)',
  noFailures: '暂无失败记录 / No failures recorded yet',
  fails: '次失败 / Fails',
  recordStart: '记录开始执行时间 / Record Start Execution Time',
  vehicleExecSuccess: '车辆执行成功时间 / Vehicle Execution Success Time',
  appFeedbackSuccess: 'APP 反馈成功时间 / APP Feedback Success Time',
  pass: '通过 / Pass',
  fail: '失败 / Fail',
  NA: '不支持 / N/A',
  syncingData: '同步数据中 / Synchronizing Data',
  processingTelemetry: '处理生产遥测数据... / Processing production telemetry...',
  validationTest: '验证测试 / Validation Test',
  placeholderVehicle: 'E.G. NDLB',
  placeholderYear: 'E.G. 24',
  placeholderVin: 'ENTER 17 DIGIT VIN',
  placeholderTester: 'Tester Name',
  placeholderMileage: 'E.G. 8888',
  // Additional labels
  backToHome: '返回首页 / Back to Home',
  historicalRecord: '历史测试记录 / Historical Test Record',
  filterRecords: '筛选测试记录 / Filter Records',
  startDate: '测试开始日期 / Start Date',
  endDate: '测试结束日期 / End Date',
  caseId: '用例编号 / Case ID',
  completed: '已完成 / Completed',
  noVisualAssets: '暂无视觉证据 / No Visual Assets Captured',
  terminateMission: '终止任务? / Terminate Mission?',
  terminateWarning: '警告：当前测试用例的数据将不会被永久保存。 / Caution: Data for the current test case will not be permanently stored.',
  dashboard: '仪表盘 / Dashboard',
  summaryStats: '统计概览 / Summary Stats',
  executionProgress: '执行进度 / Execution Progress',
  failuresByModel: '各车型失败统计 / Failures by Model',
  recentBugs: '最近缺陷 / Recent Bugs',
  notesPlaceholder: '记录测试笔记、详细的错误描述或环境异常... / Record testing notes, detailed bug descriptions, or environmental anomalies...',
  noExpectedCriteria: '未指定预期结果 / No expected criteria',
  unassigned: '未指派 / Unassigned',
  noDescription: '无描述 / No description',
  enterLocation: 'Enter Location',
  save: '保存 / Save',
  makeBug: '提交 Bug / Make Bug',
  next: '下一步 / Next',
};
