require('dotenv').config();
const mysql = require('mysql2');
const { getBeijingTime } = require('./utils.cjs');

// Initialize MySQL Database Connection Pool
const pool = mysql.createPool({
    host: process.env.DB_HOST || 'localhost',
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || 'root',
    database: process.env.DB_NAME || 'test_recorder',
    port: 3306,
    waitForConnections: true,
    connectionLimit: 10,
    queueLimit: 0,
    dateStrings: true
});

const db = pool.promise();

async function initializeDatabase() {
    try {
        // Cases Table
        await db.query(`
            CREATE TABLE IF NOT EXISTS cases (
                id INT PRIMARY KEY,
                category VARCHAR(255),
                function_category VARCHAR(255) DEFAULT '',
                \`function\` VARCHAR(255),
                content TEXT,
                type VARCHAR(50),
                expected TEXT,
                updated_at DATETIME
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // Test Sessions Table
        await db.query(`
            CREATE TABLE IF NOT EXISTS test_sessions (
                id INT PRIMARY KEY AUTO_INCREMENT,
                vehicle_model VARCHAR(255),
                model_year VARCHAR(50),
                vin VARCHAR(100),
                address VARCHAR(255),
                architecture VARCHAR(100),
                ivi_module VARCHAR(100),
                comm_module VARCHAR(100),
                package_photo LONGTEXT,
                env_photo LONGTEXT,
                tester VARCHAR(255),
                mileage VARCHAR(255),
                timestamp DATETIME(3)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // Test Results Table
        await db.query(`
            CREATE TABLE IF NOT EXISTS test_results (
                id INT PRIMARY KEY AUTO_INCREMENT,
                session_id INT,
                case_id INT,
                start_time DATETIME(3),
                car_exec_time DATETIME(3),
                app_feedback_time DATETIME(3),
                result VARCHAR(50),
                notes TEXT,
                INDEX (session_id),
                FOREIGN KEY (session_id) REFERENCES test_sessions(id) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // Bugs Table
        await db.query(`
            CREATE TABLE IF NOT EXISTS bugs (
                id INT PRIMARY KEY AUTO_INCREMENT,
                session_id INT,
                case_id INT,
                description TEXT,
                app_duration VARCHAR(50),
                timestamp DATETIME(3),
                INDEX (session_id),
                FOREIGN KEY (session_id) REFERENCES test_sessions(id) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // PDCA Columns Auto-migration
        try {
            const [cols] = await db.query("SHOW COLUMNS FROM bugs LIKE 'status'");
            if (cols.length === 0) {
                await db.query(`
                    ALTER TABLE bugs 
                    ADD COLUMN status VARCHAR(50) DEFAULT 'Plan',
                    ADD COLUMN assignee VARCHAR(100),
                    ADD COLUMN root_cause TEXT,
                    ADD COLUMN action_notes TEXT
                `);
                console.log('✅ Successfully added PDCA tracking columns to bugs table');
            }
        } catch (err) {
            console.error('⚠️ DB Migration missing for bugs:', err);
        }

        // Seed Initial Cases if empty
        const [rows] = await db.query("SELECT COUNT(*) as count FROM cases");
        if (rows[0].count === 0) {
            const initialCases = [
[
        1,
        "车辆服务",
        "蓝键功能",
        "ODD车载导航",
        "接收成功",
        "Simple",
        ""
    ],
    [
        2,
        "车辆服务",
        "蓝键功能",
        "ODD车载导航",
        "目的地在地图显示正确",
        "Simple",
        ""
    ],
    [
        3,
        "车辆服务",
        "蓝键功能",
        "ODD车载导航",
        "目的地信息显示正确",
        "Simple",
        ""
    ],
    [
        4,
        "车辆服务",
        "蓝键功能",
        "车辆实时按需诊断",
        "车辆模块诊断成功",
        "Simple",
        ""
    ],
    [
        5,
        "车辆服务",
        "蓝键功能",
        "车辆实时按需诊断",
        "公里数正确",
        "Simple",
        ""
    ],
    [
        6,
        "车辆服务",
        "蓝键功能",
        "车辆实时按需诊断",
        "机油寿命正确",
        "Simple",
        ""
    ],
    [
        7,
        "车辆服务",
        "蓝键功能",
        "车辆实时按需诊断",
        "胎压正确",
        "Simple",
        ""
    ],
    [
        8,
        "车辆服务",
        "蓝键功能",
        "闪灯鸣笛",
        "成功闪灯",
        "Simple",
        ""
    ],
    [
        9,
        "车辆服务",
        "蓝键功能",
        "闪灯鸣笛",
        "成功鸣笛",
        "Simple",
        ""
    ],
    [
        10,
        "车辆服务",
        "蓝键功能",
        "闪灯鸣笛",
        "成功闪灯鸣笛",
        "Simple",
        ""
    ],
    [
        11,
        "车辆服务",
        "蓝键功能",
        "闪灯鸣笛",
        "闪灯鸣笛30秒后自动停止(视现场环境)",
        "Simple",
        ""
    ],
    [
        12,
        "车辆服务",
        "蓝键功能",
        "车门上锁",
        "上锁成功",
        "Simple",
        ""
    ],
    [
        13,
        "车辆服务",
        "蓝键功能",
        "车门解锁",
        "解锁成功",
        "Simple",
        ""
    ],
    [
        14,
        "车辆服务",
        "蓝键功能",
        "车辆位置",
        "车辆位置正确",
        "Simple",
        ""
    ],
    [
        15,
        "车辆服务",
        "蓝键功能",
        "发送OVD诊断邮件",
        "客服发送成功",
        "Simple",
        ""
    ],
    [
        16,
        "车辆服务",
        "蓝键功能",
        "发送OVD诊断邮件",
        "邮箱收到车辆诊断邮件",
        "Simple",
        ""
    ],
    [
        17,
        "车辆服务",
        "蓝键功能",
        "发送OVD诊断邮件",
        "对比OVD数据与实车数据",
        "Simple",
        ""
    ],
    [
        18,
        "车辆服务",
        "蓝键功能",
        "发送OVD诊断邮件",
        "添加OVD截图",
        "Simple",
        ""
    ],
    [
        19,
        "车辆服务",
        "白键功能",
        "按白键观察实车反馈",
        "无反馈",
        "Simple",
        ""
    ],
    [
        20,
        "车辆服务",
        "白键功能",
        "挂断蓝键",
        "成功挂断",
        "Simple",
        ""
    ],
    [
        21,
        "车辆服务",
        "红键功能",
        "联系到安吉星紧急救援小组",
        "接入成功",
        "Simple",
        ""
    ],
    [
        22,
        "车辆服务",
        "红键功能",
        "联系到安吉星紧急救援小组",
        "获取车辆位置正确",
        "Simple",
        ""
    ],
    [
        23,
        "车辆服务",
        "红键功能",
        "联系到安吉星紧急救援小组",
        "紧急回拨成功",
        "Simple",
        ""
    ],
    [
        24,
        "车辆服务",
        "WiFi",
        "Wi-Fi SSID/密码",
        "车机屏获取SSID/密码成功",
        "Simple",
        ""
    ],
    [
        25,
        "车辆服务",
        "WiFi",
        "Wi-Fi SSID/密码",
        "车机屏修改SSID/密码成功",
        "Simple",
        ""
    ],
    [
        26,
        "车辆服务",
        "WiFi",
        "Wi-Fi SSID/密码",
        "后台修改wifi密码",
        "Simple",
        ""
    ],
    [
        27,
        "车辆服务",
        "WiFi",
        "Wi-Fi连接",
        "Wi-Fi热点可连接并正常上网",
        "Simple",
        ""
    ],
    [
        28,
        "车辆服务",
        "车机屏",
        "导航实时路况",
        "导航实时路况显示正确",
        "Simple",
        ""
    ],
    [
        29,
        "车辆服务",
        "车机屏",
        "应用程序",
        "听音乐",
        "Simple",
        ""
    ],
    [
        30,
        "车辆服务",
        "车机屏",
        "应用程序",
        "爱奇艺",
        "Simple",
        ""
    ],
    [
        31,
        "车辆服务",
        "车机屏",
        "应用程序",
        "小视频",
        "Simple",
        ""
    ],
    [
        32,
        "车辆服务",
        "车机屏",
        "应用程序",
        "拍照记录车机屏app",
        "Simple",
        ""
    ],
    [
        33,
        "车辆服务",
        "TASK",
        "TAN",
        "实车闪灯鸣笛",
        "Simple",
        ""
    ],
    [
        34,
        "车辆服务",
        "TASK",
        "TAN",
        "车机APP收到告警短信",
        "Simple",
        ""
    ],
    [
        35,
        "手机应用",
        "手机APP-iOS",
        "登录手机应用",
        "登录成功",
        "Simple",
        "打开安吉星手机app，输入正确的用户名和密码，点击登录"
    ],
    [
        36,
        "手机应用",
        "手机APP-iOS",
        "登录手机应用",
        "车辆名字显示正确",
        "Simple",
        "查看车辆名字的3种路径：1. On-左上角-车辆名字；2. On-点击查看车况-上方-车辆名字；3. On-左上角车辆切换-车辆名字"
    ],
    [
        37,
        "手机应用",
        "手机APP-iOS",
        "登录手机应用",
        "车辆图片显示正确",
        "Simple",
        "查看车辆图片的3种路径：1. On-左上角-车辆图片；2. On-点击查看车况-上方-车辆图片；3. On-左上角车辆切换-车辆名字"
    ],
    [
        38,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (熄火)",
        "刷新成功",
        "query",
        "车辆熄火，开关车门后，点击On-中间车况信息-下拉屏幕刷新车况（下拉后松手，不要短时间内频繁下拉刷新）"
    ],
    [
        39,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (熄火)",
        "手机应用显示正常",
        "Simple",
        ""
    ],
    [
        40,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "刷新成功",
        "query",
        "车辆点火后，点击On-中间车况信息-下拉屏幕刷新车况（下拉后松手，不要短时间内频繁下拉刷新），刷新成功后比对车机仪表盘和app数值"
    ],
    [
        41,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "公里数显示正确",
        "Simple",
        ""
    ],
    [
        42,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "综合续航显示正确",
        "Simple",
        ""
    ],
    [
        43,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "电动续航显示正确",
        "Simple",
        ""
    ],
    [
        44,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "剩余油量显示正确",
        "Simple",
        ""
    ],
    [
        45,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "电量显示正确",
        "Simple",
        ""
    ],
    [
        46,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "机油寿命显示正确",
        "Simple",
        ""
    ],
    [
        47,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "胎压显示正确",
        "Simple",
        ""
    ],
    [
        48,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "空滤显示正确",
        "Simple",
        ""
    ],
    [
        49,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "充电状态显示正确",
        "Simple",
        ""
    ],
    [
        50,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "仪表屏幕显示正确",
        "Simple",
        ""
    ],
    [
        51,
        "手机应用",
        "手机APP-iOS",
        "刷新车况 (点火)",
        "手机应用显示正常",
        "Simple",
        ""
    ],
    [
        52,
        "手机应用",
        "手机APP-iOS",
        "车门上锁",
        "上锁成功",
        "timing",
        "车辆熄火，开关车门后，点击On-车门上锁"
    ],
    [
        53,
        "手机应用",
        "手机APP-iOS",
        "车门上锁",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        54,
        "手机应用",
        "手机APP-iOS",
        "车门解锁",
        "解锁成功",
        "timing",
        "车辆熄火，开关车门后，点击On-车门解锁"
    ],
    [
        55,
        "手机应用",
        "手机APP-iOS",
        "车门解锁",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        56,
        "手机应用",
        "手机APP-iOS",
        "闪灯鸣笛",
        "成功闪灯",
        "timing",
        "车辆熄火，开关车门后，点击On-闪灯鸣笛-闪灯（闪灯鸣笛停止：开启主驾门或者30秒后自动停止）"
    ],
    [
        57,
        "手机应用",
        "手机APP-iOS",
        "闪灯鸣笛",
        "成功鸣笛",
        "timing",
        "车辆熄火，开关车门后，点击On-闪灯鸣笛-鸣笛（闪灯鸣笛停止：开启主驾门或者30秒后自动停止）"
    ],
    [
        58,
        "手机应用",
        "手机APP-iOS",
        "闪灯鸣笛",
        "成功闪灯鸣笛",
        "timing",
        "车辆熄火，开关车门后，点击On-闪灯鸣笛-闪灯鸣笛（闪灯鸣笛停止：开启主驾门或者30秒后自动停止）"
    ],
    [
        59,
        "手机应用",
        "手机APP-iOS",
        "闪灯鸣笛",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        60,
        "手机应用",
        "手机APP-iOS",
        "车辆远程启动",
        "远程启动成功",
        "timing",
        "车辆熄火，开关车门后，点击On-远程启动（判定条件：远程启动，钥匙车辆30M以外（感应不到），P档，车辆熄火）"
    ],
    [
        61,
        "手机应用",
        "手机APP-iOS",
        "车辆远程启动",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        62,
        "手机应用",
        "手机APP-iOS",
        "取消启动",
        "取消成功",
        "timing",
        "点击On-取消启动（上一次车辆启动必须是远程启动命令）"
    ],
    [
        63,
        "手机应用",
        "手机APP-iOS",
        "取消启动",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        64,
        "手机应用",
        "手机APP-iOS",
        "车辆远程启动",
        "一个点火周期内只能启动两次，第三次失败",
        "Simple",
        "一个点火周期只支持两次远程启动（基于安全考虑，用户从手机app上执行两次远程启动后，必须要在车端执行启动命令）"
    ],
    [
        65,
        "手机应用",
        "手机APP-iOS",
        "车辆远程启动",
        "手机应用反馈正常(第三次应显示失败)",
        "Simple",
        ""
    ],
    [
        66,
        "手机应用",
        "手机APP-iOS",
        "车辆操作历史",
        "查询正常",
        "Simple",
        "点击On-全部功能服务-右上角操作历史"
    ],
    [
        67,
        "手机应用",
        "手机APP-iOS",
        "远程后备箱控制",
        "远程开后备箱成功",
        "timing",
        "P档，和钥匙无关，点击On-后备箱开启"
    ],
    [
        68,
        "手机应用",
        "手机APP-iOS",
        "远程后备箱控制",
        "远程解锁后备箱成功",
        "timing",
        "点击On-后备箱解锁"
    ],
    [
        69,
        "手机应用",
        "手机APP-iOS",
        "远程后备箱控制",
        "远程上锁后备箱成功",
        "timing",
        "点击On-后备箱上锁"
    ],
    [
        70,
        "手机应用",
        "手机APP-iOS",
        "远程车窗控制",
        "远程开车窗成功",
        "timing",
        ""
    ],
    [
        71,
        "手机应用",
        "手机APP-iOS",
        "远程车窗控制",
        "远程关车窗成功",
        "timing",
        ""
    ],
    [
        72,
        "手机应用",
        "手机APP-iOS",
        "远程天窗控制",
        "远程开天窗成功",
        "timing",
        "P档，车辆熄火状态，点击On-天窗开启"
    ],
    [
        73,
        "手机应用",
        "手机APP-iOS",
        "远程天窗控制",
        "远程关天窗成功",
        "timing",
        "P档，车辆熄火状态，点击On-天窗关闭"
    ],
    [
        74,
        "手机应用",
        "手机APP-iOS",
        "远程空调控制",
        "远程开空调成功",
        "timing",
        ""
    ],
    [
        75,
        "手机应用",
        "手机APP-iOS",
        "远程空调控制",
        "确认温度,风速,风向功能及图标与实车一致",
        "Simple",
        ""
    ],
    [
        76,
        "手机应用",
        "手机APP-iOS",
        "远程空调控制",
        "远程急速升温成功",
        "timing",
        ""
    ],
    [
        77,
        "手机应用",
        "手机APP-iOS",
        "远程空调控制",
        "远程急速降温成功",
        "timing",
        ""
    ],
    [
        78,
        "手机应用",
        "手机APP-iOS",
        "远程空调控制",
        "远程关空调成功",
        "timing",
        ""
    ],
    [
        79,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风打开成功（所有）",
        "timing",
        ""
    ],
    [
        80,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风关闭成功（所有）",
        "timing",
        ""
    ],
    [
        81,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风打开成功（主驾）",
        "timing",
        ""
    ],
    [
        82,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风关闭成功（主驾）",
        "timing",
        ""
    ],
    [
        83,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风打开成功（副驾）",
        "timing",
        ""
    ],
    [
        84,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风关闭成功（副驾）",
        "timing",
        ""
    ],
    [
        85,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风打开成功（二排）",
        "timing",
        ""
    ],
    [
        86,
        "手机应用",
        "手机APP-iOS",
        "远程座椅通风",
        "远程座椅通风关闭成功（二排）",
        "timing",
        ""
    ],
    [
        87,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热打开成功（所有）",
        "timing",
        ""
    ],
    [
        88,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热关闭成功（所有）",
        "timing",
        ""
    ],
    [
        89,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热打开成功（主驾）",
        "timing",
        ""
    ],
    [
        90,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热关闭成功（主驾）",
        "timing",
        ""
    ],
    [
        91,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热打开成功（副驾）",
        "timing",
        ""
    ],
    [
        92,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热关闭成功（副驾）",
        "timing",
        ""
    ],
    [
        93,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热打开成功（二排）",
        "timing",
        ""
    ],
    [
        94,
        "手机应用",
        "手机APP-iOS",
        "远程座椅加热",
        "远程座椅加热关闭成功（二排）",
        "timing",
        ""
    ],
    [
        95,
        "手机应用",
        "手机APP-iOS",
        "远程方向盘加热",
        "远程方向盘加热打开成功",
        "timing",
        ""
    ],
    [
        96,
        "手机应用",
        "手机APP-iOS",
        "远程方向盘加热",
        "远程方向盘加热关闭成功",
        "timing",
        ""
    ],
    [
        97,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "车辆部件状态更新成功",
        "query",
        "打开或关闭车门/大灯/车窗/天窗/后备箱/警示灯等，点击On-中间车况信息-下拉屏幕刷新车况后，检查app车辆零部件状态和实车状态是否一致（零部件状态是在车况的图片上体现，用部件的实际位置去展现）"
    ],
    [
        98,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "车门状态正确",
        "Simple",
        ""
    ],
    [
        99,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "大灯状态正确",
        "Simple",
        ""
    ],
    [
        100,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "警示灯状态正确",
        "Simple",
        ""
    ],
    [
        101,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "车窗状态正确",
        "Simple",
        ""
    ],
    [
        102,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "天窗状态正确",
        "Simple",
        ""
    ],
    [
        103,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "后备箱状态正确",
        "Simple",
        ""
    ],
    [
        104,
        "手机应用",
        "手机APP-iOS",
        "刷新车辆部件状态",
        "远程启动状态正确",
        "Simple",
        ""
    ],
    [
        105,
        "手机应用",
        "手机APP-iOS",
        "ODD下发(熄火)",
        "点火后接收成功",
        "query",
        "车辆熄火，开关车门后，手机app点击On-地图服务-上方输入目的地-搜索-点击搜索结果-发送到车，手机发送成功后，车辆点火"
    ],
    [
        106,
        "手机应用",
        "手机APP-iOS",
        "ODD下发(熄火)",
        "目的地在地图显示正确",
        "Simple",
        "车机端显示导航信息"
    ],
    [
        107,
        "手机应用",
        "手机APP-iOS",
        "ODD下发(熄火)",
        "目的地信息显示正确",
        "Simple",
        ""
    ],
    [
        108,
        "手机应用",
        "手机APP-iOS",
        "ODD下发(点火)",
        "接收成功",
        "timing",
        "车辆点火状态下，手机app点击On-地图服务-上方输入目的地-搜索-点击搜索结果-发送到车"
    ],
    [
        109,
        "手机应用",
        "手机APP-iOS",
        "ODD下发(点火)",
        "目的地在地图显示正确",
        "Simple",
        "车机端显示导航信息"
    ],
    [
        110,
        "手机应用",
        "手机APP-iOS",
        "ODD下发(点火)",
        "目的地信息显示正确",
        "Simple",
        ""
    ],
    [
        111,
        "手机应用",
        "手机APP-iOS",
        "车辆位置",
        "定位成功",
        "query",
        "点击On-获取位置"
    ],
    [
        112,
        "手机应用",
        "手机APP-iOS",
        "车辆位置",
        "位置正确",
        "Simple",
        "和周围参照物进行对比，误差不大于100米"
    ],
    [
        113,
        "手机应用",
        "手机APP-iOS",
        "我的位置",
        "定位成功",
        "Simple",
        "点击On-获取位置-左侧圆点图标按钮"
    ],
    [
        114,
        "手机应用",
        "手机APP-iOS",
        "我的位置",
        "位置正确",
        "Simple",
        ""
    ],
    [
        115,
        "手机应用",
        "手机APP-iOS",
        "实时路况",
        "显示成功",
        "Simple",
        "点击On-获取位置-左侧红绿灯图标按钮"
    ],
    [
        116,
        "手机应用",
        "手机APP-iOS",
        "WIFI SSID/密码",
        "获取成功",
        "Simple",
        "点击On-右上角设置-车载Wi-Fi"
    ],
    [
        117,
        "手机应用",
        "手机APP-iOS",
        "WIFI SSID/密码",
        "修改成功",
        "Simple",
        "点击On-右上角设置-车载Wi-Fi"
    ],
    [
        118,
        "手机应用",
        "手机APP-iOS",
        "查询套餐包",
        "套餐包显示正常",
        "Simple",
        "我的-套餐版块-安吉星套餐-当前套餐/购买更多套餐"
    ],
    [
        119,
        "手机应用",
        "手机APP-iOS",
        "查询套餐包",
        "添加截图",
        "Simple",
        ""
    ],
    [
        120,
        "手机应用",
        "手机APP-iOS",
        "查询流量包",
        "流量包显示正常",
        "Simple",
        "我的-套餐版块-影音娱乐流量-当前套餐/购买更多流量"
    ],
    [
        121,
        "手机应用",
        "手机APP-iOS",
        "查询流量包",
        "添加截图",
        "Simple",
        ""
    ],
    [
        122,
        "手机应用",
        "手机APP-Android",
        "登录手机应用",
        "登录成功",
        "Simple",
        "打开安吉星手机app，输入正确的用户名和密码，点击登录"
    ],
    [
        123,
        "手机应用",
        "手机APP-Android",
        "登录手机应用",
        "车辆名字显示正确",
        "Simple",
        "查看车辆名字的3种路径：1. On-左上角-车辆名字；2. On-点击查看车况-上方-车辆名字；3. On-左上角车辆切换-车辆名字"
    ],
    [
        124,
        "手机应用",
        "手机APP-Android",
        "登录手机应用",
        "车辆图片显示正确",
        "Simple",
        "查看车辆图片的3种路径：1. On-左上角-车辆图片；2. On-点击查看车况-上方-车辆图片；3. On-左上角车辆切换-车辆名字"
    ],
    [
        125,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (熄火)",
        "刷新成功",
        "query",
        "车辆熄火，开关车门后，点击On-中间车况信息-下拉屏幕刷新车况（下拉后松手，不要短时间内频繁下拉刷新）"
    ],
    [
        126,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (熄火)",
        "手机应用显示正常",
        "Simple",
        ""
    ],
    [
        127,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "刷新成功",
        "query",
        "车辆点火后，点击On-中间车况信息-下拉屏幕刷新车况（下拉后松手，不要短时间内频繁下拉刷新），刷新成功后比对车机仪表盘和app数值"
    ],
    [
        128,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "公里数显示正确",
        "Simple",
        ""
    ],
    [
        129,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "综合续航显示正确",
        "Simple",
        ""
    ],
    [
        130,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "电动续航显示正确",
        "Simple",
        ""
    ],
    [
        131,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "剩余油量显示正确",
        "Simple",
        ""
    ],
    [
        132,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "电量显示正确",
        "Simple",
        ""
    ],
    [
        133,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "机油寿命显示正确",
        "Simple",
        ""
    ],
    [
        134,
        "手机应用",
        "手机APP-Android",
        "胎压显示正确",
        null,
        "Simple",
        ""
    ],
    [
        135,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "空滤显示正确",
        "Simple",
        ""
    ],
    [
        136,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "充电状态显示正确",
        "Simple",
        ""
    ],
    [
        137,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "仪表屏幕显示正确",
        "Simple",
        ""
    ],
    [
        138,
        "手机应用",
        "手机APP-Android",
        "刷新车况 (点火)",
        "手机应用显示正常",
        "Simple",
        ""
    ],
    [
        139,
        "手机应用",
        "手机APP-Android",
        "车门上锁",
        "上锁成功",
        "timing",
        "车辆熄火，开关车门后，点击On-车门上锁"
    ],
    [
        140,
        "手机应用",
        "手机APP-Android",
        "车门上锁",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        141,
        "手机应用",
        "手机APP-Android",
        "车门解锁",
        "解锁成功",
        "timing",
        "车辆熄火，开关车门后，点击On-车门解锁"
    ],
    [
        142,
        "手机应用",
        "手机APP-Android",
        "车门解锁",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        143,
        "手机应用",
        "手机APP-Android",
        "闪灯鸣笛",
        "成功闪灯",
        "timing",
        "车辆熄火，开关车门后，点击On-闪灯鸣笛-闪灯（闪灯鸣笛停止：开启主驾门或者30秒后自动停止）"
    ],
    [
        144,
        "手机应用",
        "手机APP-Android",
        "闪灯鸣笛",
        "成功鸣笛",
        "timing",
        "车辆熄火，开关车门后，点击On-闪灯鸣笛-鸣笛（闪灯鸣笛停止：开启主驾门或者30秒后自动停止）"
    ],
    [
        145,
        "手机应用",
        "手机APP-Android",
        "闪灯鸣笛",
        "成功闪灯鸣笛",
        "timing",
        "车辆熄火，开关车门后，点击On-闪灯鸣笛-闪灯鸣笛（闪灯鸣笛停止：开启主驾门或者30秒后自动停止）"
    ],
    [
        146,
        "手机应用",
        "手机APP-Android",
        "闪灯鸣笛",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        147,
        "手机应用",
        "手机APP-Android",
        "车辆远程启动",
        "远程启动成功",
        "timing",
        "车辆熄火，开关车门后，点击On-远程启动（判定条件：远程启动，钥匙车辆30M以外（感应不到），P档，车辆熄火）"
    ],
    [
        148,
        "手机应用",
        "手机APP-Android",
        "车辆远程启动",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        149,
        "手机应用",
        "手机APP-Android",
        "取消启动",
        "取消成功",
        "timing",
        "点击On-取消启动（上一次车辆启动必须是远程启动命令）"
    ],
    [
        150,
        "手机应用",
        "手机APP-Android",
        "取消启动",
        "手机应用反馈正常",
        "Simple",
        ""
    ],
    [
        151,
        "手机应用",
        "手机APP-Android",
        "车辆远程启动",
        "一个点火周期内只能启动两次，第三次失败",
        "Simple",
        "一个点火周期只支持两次远程启动（基于安全考虑，用户从手机app上执行两次远程启动后，必须要在车端执行启动命令）"
    ],
    [
        152,
        "手机应用",
        "手机APP-Android",
        "车辆远程启动",
        "手机应用反馈正常(第三次应显示失败)",
        "Simple",
        ""
    ],
    [
        153,
        "手机应用",
        "手机APP-Android",
        "车辆操作历史",
        "查询正常",
        "Simple",
        "点击On-全部功能服务-右上角操作历史"
    ],
    [
        154,
        "手机应用",
        "手机APP-Android",
        "远程后备箱控制",
        "远程开后备箱成功",
        "timing",
        "P档，和钥匙无关，点击On-后备箱开启"
    ],
    [
        155,
        "手机应用",
        "手机APP-Android",
        "远程后备箱控制",
        "远程解锁后备箱成功",
        "timing",
        "点击On-后备箱解锁"
    ],
    [
        156,
        "手机应用",
        "手机APP-Android",
        "远程后备箱控制",
        "远程上锁后备箱成功",
        "timing",
        "点击On-后备箱上锁"
    ],
    [
        157,
        "手机应用",
        "手机APP-Android",
        "远程车窗控制",
        "远程开车窗成功",
        "timing",
        ""
    ],
    [
        158,
        "手机应用",
        "手机APP-Android",
        "远程车窗控制",
        "远程关车窗成功",
        "timing",
        ""
    ],
    [
        159,
        "手机应用",
        "手机APP-Android",
        "远程天窗控制",
        "远程开天窗成功",
        "timing",
        "P档，车辆熄火状态，点击On-天窗开启"
    ],
    [
        160,
        "手机应用",
        "手机APP-Android",
        "远程天窗控制",
        "远程关天窗成功",
        "timing",
        "P档，车辆熄火状态，点击On-天窗关闭"
    ],
    [
        161,
        "手机应用",
        "手机APP-Android",
        "远程空调控制",
        "远程开空调成功",
        "timing",
        ""
    ],
    [
        162,
        "手机应用",
        "手机APP-Android",
        "远程空调控制",
        "确认温度,风速,风向功能及图标与实车一致",
        "Simple",
        ""
    ],
    [
        163,
        "手机应用",
        "手机APP-Android",
        "远程空调控制",
        "远程急速升温成功",
        "timing",
        ""
    ],
    [
        164,
        "手机应用",
        "手机APP-Android",
        "远程空调控制",
        "远程急速降温成功",
        "timing",
        ""
    ],
    [
        165,
        "手机应用",
        "手机APP-Android",
        "远程空调控制",
        "远程关空调成功",
        "timing",
        ""
    ],
    [
        166,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风打开成功（所有）",
        "timing",
        ""
    ],
    [
        167,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风关闭成功（所有）",
        "timing",
        ""
    ],
    [
        168,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风打开成功（主驾）",
        "timing",
        ""
    ],
    [
        169,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风关闭成功（主驾）",
        "timing",
        ""
    ],
    [
        170,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风打开成功（副驾）",
        "timing",
        ""
    ],
    [
        171,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风关闭成功（副驾）",
        "timing",
        ""
    ],
    [
        172,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风打开成功（二排）",
        "timing",
        ""
    ],
    [
        173,
        "手机应用",
        "手机APP-Android",
        "远程座椅通风",
        "远程座椅通风关闭成功（二排）",
        "timing",
        ""
    ],
    [
        174,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热打开成功（所有）",
        "timing",
        ""
    ],
    [
        175,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热关闭成功（所有）",
        "timing",
        ""
    ],
    [
        176,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热打开成功（主驾）",
        "timing",
        ""
    ],
    [
        177,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热关闭成功（主驾）",
        "timing",
        ""
    ],
    [
        178,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热打开成功（副驾）",
        "timing",
        ""
    ],
    [
        179,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热关闭成功（副驾）",
        "timing",
        ""
    ],
    [
        180,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热打开成功（二排）",
        "timing",
        ""
    ],
    [
        181,
        "手机应用",
        "手机APP-Android",
        "远程座椅加热",
        "远程座椅加热关闭成功（二排）",
        "timing",
        ""
    ],
    [
        182,
        "手机应用",
        "手机APP-Android",
        "远程方向盘加热",
        "远程方向盘加热打开成功",
        "timing",
        ""
    ],
    [
        183,
        "手机应用",
        "手机APP-Android",
        "远程方向盘加热",
        "远程方向盘加热关闭成功",
        "timing",
        ""
    ],
    [
        184,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "车辆部件状态更新成功",
        "query",
        "打开或关闭车门/大灯/车窗/天窗/后备箱/警示灯等，点击On-中间车况信息-下拉屏幕刷新车况后，检查app车辆零部件状态和实车状态是否一致（零部件状态是在车况的图片上体现，用部件的实际位置去展现）"
    ],
    [
        185,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "车门状态正确",
        "Simple",
        ""
    ],
    [
        186,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "大灯状态正确",
        "Simple",
        ""
    ],
    [
        187,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "警示灯状态正确",
        "Simple",
        ""
    ],
    [
        188,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "车窗状态正确",
        "Simple",
        ""
    ],
    [
        189,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "天窗状态正确",
        "Simple",
        ""
    ],
    [
        190,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "后备箱状态正确",
        "Simple",
        ""
    ],
    [
        191,
        "手机应用",
        "手机APP-Android",
        "刷新车辆部件状态",
        "远程启动状态正确",
        "Simple",
        ""
    ],
    [
        192,
        "手机应用",
        "手机APP-Android",
        "ODD下发(熄火)",
        "点火后接收成功",
        "query",
        "车辆熄火，开关车门后，手机app点击On-地图服务-上方输入目的地-搜索-点击搜索结果-发送到车，手机发送成功后，车辆点火"
    ],
    [
        193,
        "手机应用",
        "手机APP-Android",
        "ODD下发(熄火)",
        "目的地在地图显示正确",
        "Simple",
        "车机端显示导航信息"
    ],
    [
        194,
        "手机应用",
        "手机APP-Android",
        "ODD下发(熄火)",
        "目的地信息显示正确",
        "Simple",
        ""
    ],
    [
        195,
        "手机应用",
        "手机APP-Android",
        "ODD下发(点火)",
        "接收成功",
        "timing",
        "车辆点火状态下，手机app点击On-地图服务-上方输入目的地-搜索-点击搜索结果-发送到车"
    ],
    [
        196,
        "手机应用",
        "手机APP-Android",
        "目的地在地图显示正确",
        "车机端显示导航信息",
        "Simple",
        ""
    ],
    [
        197,
        "手机应用",
        "手机APP-Android",
        "目的地信息显示正确",
        "",
        "Simple",
        ""
    ],
    [
        198,
        "手机应用",
        "手机APP-Android",
        "车辆位置",
        "定位成功",
        "query",
        "点击On-获取位置"
    ],
    [
        199,
        "手机应用",
        "手机APP-Android",
        "车辆位置",
        "位置正确",
        "Simple",
        "和周围参照物进行对比，误差不大于100米"
    ],
    [
        200,
        "手机应用",
        "手机APP-Android",
        "我的位置",
        "定位成功",
        "Simple",
        "点击On-获取位置-左侧圆点图标按钮"
    ],
    [
        201,
        "手机应用",
        "手机APP-Android",
        "我的位置",
        "位置正确",
        "Simple",
        ""
    ],
    [
        202,
        "手机应用",
        "手机APP-Android",
        "实时路况",
        "显示成功",
        "Simple",
        "点击On-获取位置-左侧红绿灯图标按钮"
    ],
    [
        203,
        "手机应用",
        "手机APP-Android",
        "WIFI SSID/密码",
        "获取成功",
        "Simple",
        "点击On-右上角设置-车载Wi-Fi"
    ],
    [
        204,
        "手机应用",
        "手机APP-Android",
        "WIFI SSID/密码",
        "修改成功",
        "Simple",
        "点击On-右上角设置-车载Wi-Fi"
    ],
    [
        205,
        "手机应用",
        "手机APP-Android",
        "查询套餐包",
        "套餐包显示正常",
        "Simple",
        "我的-套餐版块-安吉星套餐-当前套餐/购买更多套餐"
    ],
    [
        206,
        "手机应用",
        "手机APP-Android",
        "查询套餐包",
        "添加截图",
        "Simple",
        ""
    ],
    [
        207,
        "手机应用",
        "手机APP-Android",
        "查询流量包",
        "流量包显示正常",
        "Simple",
        "我的-套餐版块-影音娱乐流量-当前套餐/购买更多流量"
    ],
    [
        208,
        "手机应用",
        "手机APP-Android",
        "查询流量包",
        "添加截图",
        "Simple",
        ""
    ]
];

            for (const c of initialCases) {
                await db.query(
                    "INSERT INTO cases (id, category, function_category, `function`, content, type, expected, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    [...c, getBeijingTime()]
                );
            }
            console.log('Initial cases seeded.');
        }

        // --- Migrations for DATETIME(3) precision ---
        const migrations = [
            { table: 'test_sessions', col: 'timestamp', spec: 'DATETIME(3)' },
            { table: 'test_results', col: 'start_time', spec: 'DATETIME(3)' },
            { table: 'test_results', col: 'car_exec_time', spec: 'DATETIME(3)' },
            { table: 'test_results', col: 'app_feedback_time', spec: 'DATETIME(3)' },
            { table: 'bugs', col: 'timestamp', spec: 'DATETIME(3)' }
        ];

        for (const m of migrations) {
            try {
                // Check current type by querying information_schema
                const [info] = await db.query(
                    "SELECT DATA_TYPE, DATETIME_PRECISION FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?",
                    [process.env.DB_NAME || 'test_recorder', m.table, m.col]
                );
                if (info.length > 0 && info[0].DATETIME_PRECISION !== 3) {
                    await db.query(`ALTER TABLE ${m.table} MODIFY COLUMN ${m.col} ${m.spec}`);
                    console.log(`Migration: Upgraded ${m.table}.${m.col} to ${m.spec}`);
                }
            } catch (err) {
                console.warn(`Migration skipped/failed for ${m.table}.${m.col}:`, err.message);
            }
        }

        // Migration: Add tester column if it doesn't exist
        try {
            const [columns] = await db.query("SHOW COLUMNS FROM test_sessions LIKE 'tester'");
            if (columns.length === 0) {
                await db.query("ALTER TABLE test_sessions ADD COLUMN tester VARCHAR(255) AFTER env_photo");
                console.log('Migration: Added tester column to test_sessions table.');
            }
        } catch (migrationErr) {
            console.error('Migration error (tester column):', migrationErr.message);
        }

        // Migration: Add mileage column if it doesn't exist
        try {
            const [columns] = await db.query("SHOW COLUMNS FROM test_sessions LIKE 'mileage'");
            if (columns.length === 0) {
                await db.query("ALTER TABLE test_sessions ADD COLUMN mileage VARCHAR(255) AFTER tester");
                console.log('Migration: Added mileage column to test_sessions table.');
            }
        } catch (migrationErr) {
            console.error('Migration error (mileage column):', migrationErr.message);
        }

        console.log('MySQL Database initialized successfully.');
    } catch (err) {
        console.error('Database initialization error:', err.message);
    }
}

module.exports = { pool, db, initializeDatabase };
